name: Build and Deploy VM

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build VM Image
        run: |
          az image create --resource-group myResourceGroup --name myImage --source mySource

      - name: Deploy VM
        run: |
          az vm create --resource-group myResourceGroup --name myVM --image myImage
